baseURL = "http://example.org/"
languageCode = "en-us"
title = "A Financial Education"
theme = "ananke"

[params]
  description = "Learning how-to Fi/RE"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/wall-st.jpg"